PUT http://192.168.1.7:5000/self_order/add_shopping_list/1011
Content-Type: application/json

{"item": "hellowld", "quantity": "1"}


### GET
GET http://192.168.1.7:5000/self_order/get_shopping_list/1011
Accept: application/json


