# -*- coding: utf-8 -*-
"""data_grabber.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15aD54jLoQMYZU6Os5uA4mwM2wtUpgZR8
"""



from google.colab import drive
drive.mount('/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/dataset/

from google.colab import files
files.upload()

!pip install --upgrade --force-reinstall --no-deps kaggle

!pip install -q kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!ls ~/.kaggle
!chmod 600 /root/.kaggle/kaggle.json

!kaggle competitions download -c imagenet-object-localization-challenge -p /content/drive/MyDrive/dataset/

